name: devsecops-infra
on: push
jobs:
    devsecops-inf:
        runs-on: ubuntu-latest
        steps: 
        - name: Clone the repo
          uses: actions/checkout@v6        
          with:     
           fetch-depth: 0
           
        - name: Secret scanning
          uses: gitleaks/gitleaks-action@v2
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
        - name: setup Terraform           
          uses: hashicorp/setup-terraform@v4          
       
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET}}
            aws-region: ap-south-1
          
        - name: verify Terraform
          run: terraform version
        
        - name: Run Terraform init
          run: terraform init
          
        - name: run Terraform format
          run: terraform fmt
          
        - name: run Terraform validate
          run: terraform validate
          
        - name: run Terraform plan
          run: terraform plan
          
        - name: run Terraform apply
          run: terraform apply -auto-approve
